### ISSUE TITLE
如果能解析XG的数据文件就好了

### ISSUE THREAD

**Issue by senseab** [GAIAProject/gembHost#1]
XG-50的数据文件为：sxgbin41.tbl 和 sxgwave4.tbl
XG2006LE的数据文件为：sxgbnw6l.tbl 和 sxgdat6l.tbl

文件格式大不一样！我最近在尝试反汇编S-YXG50.dll（vst）以了解它是怎么使用这两个文件的 但是还没有结果（这玩意是用C++写的）
如果能出个lib可以加载这几个文件，那就可以实现在Linux下完美的听XG了

**Comment by rgwan** [comment]
抱歉,其实对XG的_波表支持_已经不在日程里了.现在采样器本身的工作会类似Kontakt,而XG的支持的规划是由Plugin Host(也就是embHost,embHost的目标平台是资源受限系统,比如rpi)加载各类LV2插件实现.

至于对雅马哈的波表数据的读取,我没有干它的计划.毕竟就4M音源,音质比较醉,那个波表我在DB60XG的ROM中读出过,如果你想要可以加我TG @rgwan,我发给你.

还在码GAIASampler,等采样器能用了,XG也就提上日程了~

**Comment by rgwan** [comment]
另外读出雅马哈那套音色和完美听XG区别很大.....XG有很丰富的系统信息,如果仅仅兼容音色选择(也许还做不到),效果也是大打折扣的..

**Comment by senseab** [comment]
但是 XG 有两个文件，一个是波表，一个是bin （sxgbin41.tlb） 不知道这个bin
是不是真正的主控程序

不过我倒是在timidity上实现了XG音色兼容 https://github.com/tonychee7000/timidity-xg-conf

在 2016年03月25日 08:53, ZhiYuan Wan 写道:

**Comment by senseab** [comment]
我又想了一下，其实你的思路是最合适的@rgwan 
如果有更好的音色，其实也没有必要非得去兼容一个老古董，正像你说的，毕竟一个4M的数据库也不可能有太好的音质，11M的也一样
我现在手里的soundfont大的也有1G，平时用的多的也大多是200M+的文件

另外我有必要入一个XG的硬件音源吗(比如MU2000)

**Comment by rgwan** [comment]
@tonychee7000 我觉得对非音乐制作人而言，没必要入硬件音源，因为目前仅支持XG的硬音源几乎都是古董了，比如MU系列和CBX系列。另外，就算对于音乐制作人，入硬音源还真不如升级下系统配置，买点好的采样库。不过如果一定要入支持XG的音源，我的建议是考虑现在雅马哈的PSR-Sx70系列键盘，或者考虑TYROS系列键盘（这部分键盘主要为实时表演而设计，对XG的兼容非常好，只是很多音色有很大的升级，听起来不会很像以前的老XG），如果你觉得键盘太占地方，可以考虑MOTIF RACK。如果说用于音乐制作的话，个人建议还是买PSR系列键盘比较好。但是如果单纯就为听几个MIDI的话，这种上五六千的键盘就显得非常不值了。但是如果单纯为了情怀以及老XG的兼容考虑，我个人的建议是可以入手MU10或者 MU50/90。这类二手价格很低，性能也还过得去。如果对电子技术比较熟悉的，也可以收DB60XG(XR385)或者DB50XG来改制XG音源（我读出的XG音色库就是从DB50XG上读出的）。

我这个项目旨在为Linux创建一个音乐人使用，便捷高效而扩展性强的数字音频工作站平台（也有实时表演的计划，其实这个host也就是为了实时表演而生）。也是源于我对Rosegarden/Ardour/LMMS的各种不满意……我现在使用的DAW是Cubase，即使是Cubase5也比Ardour好很多。Ardour各种崩溃，还有蛋疼的MIDI设计已经让我难以忍受。其他Linux DAW也是差不多的情况。所以我才想到开始这个项目:D。

**Comment by senseab** [comment]
@rgwan 考虑了一下，我打算入一个支持XG的MIDI键盘，但应该会考虑二手或者稍微古董的琴，其实平时除了听一部分XG(现在是用wine来解决这个问题)，也会尝试点创作

**Comment by senseab** [comment]
希望以后我也能贡献代码(不过目前我水平还很渣)

**Comment by rgwan** [comment]
@tonychee7000 我大概想3000左右出台PSR-S650,有意吗?

**Comment by senseab** [comment]
现在我还在租房子，毕竟要搬家还是不方便
不过能不能在闲鱼上出个链接？然后可以发邮件给我 tonychee1989@gmail.com

在 2016年03月27日 21:45, ZhiYuan Wan 写道:

**Comment by rgwan** [comment]
@tonychee7000 大概得等我暑假回南昌才能出~急要可以考虑CBX系列或者PSR-S550二手~

**Comment by senseab** [comment]
没事，不着急，我其实也得考虑考虑，毕竟吃死工资的人，我也比较担心下个月没法吃饭 XD

**Comment by nikitalita** [comment]
@rgwan what happened to this project? Is there an alternative repository location?
